module.exports = {
  plugins: ['@stylistic/stylelint-plugin', 'stylelint-order'],
  rules: {
    'block-no-empty': true,
    'color-no-invalid-hex': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-no-important': true,
    'property-no-unknown': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-max-id': 0,
    'unit-no-unknown': true,
    'color-hex-length': 'short',
    'length-zero-no-unit': true,
    'selector-pseudo-element-colon-notation': 'double',
    'rule-empty-line-before': ['always', {
      except: ['first-nested'],
      ignore: ['after-comment'],
    }],
    'order/properties-alphabetical-order': true,
    '@stylistic/indentation': 2,
    '@stylistic/block-opening-brace-space-before': 'always',
    '@stylistic/block-opening-brace-newline-after': 'always',
    '@stylistic/block-closing-brace-newline-before': 'always',
    '@stylistic/declaration-colon-space-after': 'always-single-line',
    '@stylistic/declaration-block-semicolon-newline-after': 'always',
    '@stylistic/declaration-block-trailing-semicolon': 'always',
    '@stylistic/selector-list-comma-newline-after': 'always',
    '@stylistic/selector-combinator-space-before': 'always',
    '@stylistic/selector-combinator-space-after': 'always',
    '@stylistic/string-quotes': 'single',
    '@stylistic/number-leading-zero': 'always',
    '@stylistic/no-eol-whitespace': true,
  },
};
